In [ ]:
import numpy

In [ ]:
numpy.version.full_version

'2.0.2'

In [ ]:
import numpy as np
a = np.array([0,1,2,3,4,5])
print(a)

[0 1 2 3 4 5]


In [ ]:
a.ndim

1

In [ ]:
a.shape

(6,)

In [ ]:
b = a.reshape((3,2))
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
b.ndim

2

In [ ]:
b.shape

(3, 2)

In [ ]:
b[1][0]=77

In [ ]:
print(b)

[[ 0  1]
 [77  3]
 [ 4  5]]


In this case, we have modified the value 2 to 77 in b, and we can immediately see  
the same change reflected in a as well. Keep that in mind whenever you need a  
true copy.

In [ ]:
print(a)

[ 0  1 77  3  4  5]


In [ ]:
c = a.reshape((3,2)).copy()

In [ ]:
print(c)

[[ 0  1]
 [77  3]
 [ 4  5]]


In [ ]:
c[0][0] = -99

In [ ]:
print(a)

[ 0  1 77  3  4  5]


In [ ]:
print(c)

[[-99   1]
 [ 77   3]
 [  4   5]]


Here, c and a are totally independent copies.

In [ ]:
a*2

array([  0,   2, 154,   6,   8,  10])

In [ ]:
a**2

array([   0,    1, 5929,    9,   16,   25])

### Ordinary Python lists

In [ ]:
[1,2,3,4,5]*5

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
[1,2,3,4,5]**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

# Indexing

### In addition to normal list indexing, it allows us to use arrays themselves as indices.

In [ ]:
a[np.array([2,3,4])]

array([77,  3,  4])

### In addition to the fact that conditions are now propagated to the individual elements,
we gain a very convenient way to access our data.

In [ ]:
a>4

array([False, False,  True, False, False,  True])

In [ ]:
a[a>4]

array([77,  5])

### This can also be used to trim outliers.

In [ ]:
a[a>4] = 4

### there is a special clip function for it, clipping the values
at both ends of an interval with one function call as follows

In [ ]:
a.clip(0,3)

array([0, 1, 3, 3, 3, 3])

# Handling non-existing values

In [ ]:
c = np.array([1, 2, np.nan, 3, 4])

In [ ]:
print(c)

[ 1.  2. nan  3.  4.]


In [ ]:
np.isnan(c)

array([False, False,  True, False, False])

In [ ]:
c[~np.isnan(c)]

array([1., 2., 3., 4.])

In [ ]:
np.mean(c[~np.isnan(c)])

np.float64(2.5)

## Comparing runtime behaviors

In [ ]:
import timeit

In [ ]:
normal_py_sec = timeit.timeit('sum(x*x for x in range(1000))',
                              number=10000)
naive_np_sec = timeit.timeit('sum(na*na)',
                             setup="import numpy as np; na=np.arange(1000)",
                             number=10000)
good_np_sec = timeit.timeit('na.dot(na)',
                            setup="import numpy as np; na=np.arange(1000)",
                            number=10000)
print("Normal Python: %f sec"%normal_py_sec)
print("Naive NumPy: %f sec"%naive_np_sec)
print("Good NumPy: %f sec"%good_np_sec)

In [ ]:
a.dtype

In [ ]:
np.array([1, "stringy"])

In [ ]:
np.array([1, "stringy", set([1,2,3])])