In [1]:
import numpy as np

In [2]:
G=np.zeros(10)
print(G)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
print(np.__version__)

2.0.2


In [27]:
F=np.zeros((10,10))
print(F)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [30]:
F=np.pad(F,pad_width=2,mode='constant',constant_values=24)
print(F)

[[24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24.
  24. 24. 24. 24. 24. 24. 24. 24.]
 [24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24.
  24. 24. 24. 24. 24. 24. 24. 24.]
 [24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24.
  24. 24. 24. 24. 24. 24. 24. 24.]
 [24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24.
  24. 24. 24. 24. 24. 24. 24. 24.]
 [24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24.
  24. 24. 24. 24. 24. 24. 24. 24.]
 [24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24.
  24. 24. 24. 24. 24. 24. 24. 24.]
 [24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24.
  24. 24. 24. 24. 24. 24. 24. 24.]
 [24. 24. 24. 24. 24. 24. 24.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1. 24. 24. 24. 24. 24. 24. 24.]
 [24. 24. 24. 24. 24. 24. 24.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   1. 24. 24. 24. 24. 24. 24. 24.]
 [24. 24. 24. 24. 2

In [6]:
print("%d bytes " % (G.size*G.itemsize))

80 bytes 


In [7]:
print("%d bytes " % (F.size*F.itemsize))

1568 bytes 


In [8]:
np.info(np.zeros)

zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Also
--------

In [9]:
G[8]=45
print(G)

[ 0.  0.  0.  0.  0.  0.  0.  0. 45.  0.]


In [10]:
M=np.arange(5,10,2)
print(M)

[5 7 9]


In [11]:
M[1]=85
print(M)

[ 5 85  9]


In [12]:
M[::-1]

array([ 9, 85,  5])

In [13]:
AM= np.arange(9).reshape(3,3)

In [14]:
print(AM)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
p=np.nonzero([15,95,28,0,0,0,19,3585]) #non zero element ki index
print(p)

(array([0, 1, 2, 6, 7]),)


In [17]:
d=np.eye(3) #identity matrix - 1 at diag
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
k=np.random.random((10,10))
print(k)

[[0.36578656 0.20199797 0.39192032 0.22810345 0.38364246 0.63012185
  0.80813819 0.23152951 0.47332159 0.44308015]
 [0.795687   0.25278189 0.57950346 0.56538803 0.75063005 0.68947205
  0.11804493 0.45435642 0.72136433 0.17503295]
 [0.2033019  0.44969662 0.344697   0.06414127 0.12570547 0.77262318
  0.98448483 0.56797681 0.05294922 0.60582253]
 [0.69397691 0.54075748 0.43032009 0.24429803 0.71898189 0.78627771
  0.33819752 0.59875609 0.20412103 0.72754223]
 [0.85435957 0.24072868 0.68188041 0.16861244 0.66432249 0.7317811
  0.84250011 0.6696998  0.97897414 0.62101072]
 [0.78548456 0.15750989 0.10725011 0.02079573 0.79030676 0.47093494
  0.64091586 0.0687617  0.13432917 0.05523831]
 [0.76267876 0.87275558 0.46074784 0.06490709 0.33548512 0.53137768
  0.61296671 0.71529713 0.16850719 0.69222482]
 [0.82696559 0.58859545 0.86901837 0.06643552 0.09320784 0.00590352
  0.68000046 0.10634157 0.10522821 0.74588381]
 [0.5495139  0.51255931 0.0644546  0.55977979 0.94551373 0.73190338
  0.55039575 

In [20]:
kmin=k.min()
print(kmin)

0.005903517268336489


In [21]:
kmin,kmax=k.min(),k.max()
print(k.mean())

0.48783436373862726


In [25]:
f=np.ones((10,10))
f[1:-1,1:-1]=95
print(f)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1. 95. 95. 95. 95. 95. 95. 95. 95.  1.]
 [ 1. 95. 95. 95. 95. 95. 95. 95. 95.  1.]
 [ 1. 95. 95. 95. 95. 95. 95. 95. 95.  1.]
 [ 1. 95. 95. 95. 95. 95. 95. 95. 95.  1.]
 [ 1. 95. 95. 95. 95. 95. 95. 95. 95.  1.]
 [ 1. 95. 95. 95. 95. 95. 95. 95. 95.  1.]
 [ 1. 95. 95. 95. 95. 95. 95. 95. 95.  1.]
 [ 1. 95. 95. 95. 95. 95. 95. 95. 95.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [33]:
j=np.diag(1+np.arange(4),k=-1)
print(j)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [35]:
y=np.zeros((5,5),dtype=int)
y[1::2,::2]=1
y[::2,1::2]=1
print(y)

[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]


In [38]:
e=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(e)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [36]:
# (10,7,8)

print(np.unravel_index(99,(10,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


In [39]:
color=np.dtype([("r",np.ubyte),
                ("g",np.ubyte),
                ("b",np.ubyte),
                ("a",np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [40]:
K=np.matmul(np.ones((5,3)),np.ones((3,2)))
print(K)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [42]:
l=np.arange(10)
l[(1<l) & (l<=6)] *= -1
print(l)

[ 0  1 -2 -3 -4 -5 -6  7  8  9]


In [2]:
print(sum(range(5),-1))

9
